name: Docs

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:
  

jobs:
  build:
    name: docs
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      pages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      
      - name: Generate API documentation
        run: |
          ./gradlew dokkaHtml
  
      - name: Deploy API documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html
          target-folder: docs
